homepage:
    path: /homepage
    defaults: {_controller: ninfacBundle:Default:login}

ninfac_login:
    path:   /login
    defaults: {_controller: ninfacBundle:Default:login}

ninfac_home:
    path:   /
    defaults: {_controller: ninfacBundle:Default:index}

ninfac_logout:
    path:   /logout
    defaults: {_controller: ninfacBundle:Default:logout}


ninfac:
    resource: "@ninfacBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

blog_show:
    path:   /blow
    defaults: {_controller: ninfacBundle:Default:blow}

    
about:
    path:   /about
    defaults: {_controller: ninfacBundle:Default:about}
    
    
edit_profile:
    path:   /profile
    defaults: {_controller: ninfacBundle:Default:profile}
    
    
    
registro_homepage:    
    path:   /profile
    defaults: {_controller: ninfacBundle:Default:profile}
   
        